# ---
# from md_core.fix_cs1.bots.temps_list import ref_temps
# from md_core.fix_cs1.bots.temps_list import in_params_en, in_params_ar
# ---
in_params_en = [
    "journal",
    "magazine",
    "newspaper",
    "periodical",
    "website",
    "work",
]
# ---
in_params_ar = [
    "journal",
    "magazine",
    "nespaper",
    "newpaper",
    "news",
    "news-paper",
    "newspaper",
    "periodical",
    "site",
    "website",
    "work",
    "اسم الدورية",
    "اسم الصحيفة",
    "اسم المجلة",
    "اسم الموقع",
    "الصحيفة",
    "العمل",
    "المجلة",
    "الموقع الرسمي",
    "الموقع",
    "جريدة",
    "دورية",
    "صحيفة",
    "عمل",
    "مجلة",
    "من عمل",
    "موقع",
]
# ---
ref_temps = [
    "Cite web",
    "Cite thesis",
    "Cite techreport",
    "Cite ssrn",
    "Cite speech",
    "Cite sign",
    "Cite serial",
    "Cite report",
    "Cite press",
    "Cite press release",
    "Cite podcast",
    "Cite newsgroup",
    "Cite news",
    "Cite map",
    "Cite mailing list",
    "Cite magazine",
    "Cite journal",
    "Cite interview",
    "Cite episode",
    "Cite encyclopedia",
    "Cite conference",
    "Cite book",
    "Cite bioRxiv",
    "Cite arxiv",
    "Cite arXiv",
    "Cite ChemRxiv",
    "Cite AV media",
    "Cite AV media notes",
    "Citation",
]
# ---
ref_temps = [x.lower() for x in ref_temps]
